name: Deploy Workflows
on:
  push:
    branches:
      - main
    paths:
      - "apps/workflows/**"
      - "packages/db/**"
      - "packages/emails/**"
      - "packages/utils/**"
      - "packages/tsconfig/**"

env:
  APP_NAME: zk-openstatus-workflows

jobs:
  deploy-workflows:
    name: Deploy Workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set Fly.io Secrets
        run: |
          flyctl secrets set -a ${{ env.APP_NAME }} \
          NODE_ENV=production \
          PORT=3000 \
          GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
          GCP_CLIENT_EMAIL=${{ secrets.GCP_CLIENT_EMAIL }} \
          GCP_PRIVATE_KEY=${{ secrets.GCP_PRIVATE_KEY }} \
          GCP_LOCATION=${{ secrets.GCP_LOCATION }} \
          CRON_SECRET=${{ secrets.CRON_SECRET }} \
          SITE_URL=${{ secrets.SITE_URL }} \
          DATABASE_URL=${{ secrets.DATABASE_URL }} \
          DATABASE_AUTH_TOKEN=${{ secrets.DATABASE_AUTH_TOKEN }} \
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
          TINY_BIRD_API_KEY=${{ secrets.TINY_BIRD_API_KEY }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy Workflows
        run: |
          flyctl deploy --config apps/workflows/fly.toml \
          --dockerfile apps/workflows/Dockerfile --remote-only --wait-timeout=500
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
