name: Fly Deploy Workflows
on:
  push:
    branches:
      - main
    paths:
      - "apps/workflows/**"
      - "packages/db/**"
      - "packages/emails/**"
      - "packages/utils/**"
      - "packages/tsconfig/**"
jobs:
  deploy-workflows:
    name: Deploy Workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Workflows
        run: |
          flyctl deploy --remote-only --wait-timeout=500 --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
