name: Fly Deploy screenshot-service
on:
  push:
    branches:
      - main
    paths:
      - "apps/screenshot-service/**"
jobs:
  deploy-screenshot-service:
    name: Deploy screenshot-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Set Fly.io Secrets
        run: |
          flyctl secrets set \
          R2_TOKEN=${{ secrets.R2_TOKEN }} \
          R2_URL=${{ secrets.R2_URL }} \
          R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }} \
          R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }} \
          HEADER_TOKEN=${{ secrets.HEADER_TOKEN }} \
          QSTASH_SIGNING_SECRET=${{ secrets.QSTASH_SIGNING_SECRET }} \
          QSTASH_NEXT_SIGNING_SECRET=${{ secrets.QSTASH_NEXT_SIGNING_SECRET }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy screenshot-service
        run: |
          flyctl deploy --config apps/screenshot-service/fly.toml \
          --dockerfile apps/screenshot-service/Dockerfile --remote-only --wait-timeout=500
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
