name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set Fly.io Secrets
        run: |
          flyctl secrets set \
          DATABASE_URL=${{ secrets.DATABASE_URL }} \
          DATABASE_AUTH_TOKEN=${{ secrets.DATABASE_AUTH_TOKEN }} \
          UNKEY_TOKEN=${{ secrets.UNKEY_TOKEN }} \
          TINY_BIRD_API_KEY=${{ secrets.TINY_BIRD_API_KEY }} \
          UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }} \
          UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }} \
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
          TWILLIO_AUTH_TOKEN=${{ secrets.TWILLIO_AUTH_TOKEN }} \
          TWILLIO_ACCOUNT_ID=${{ secrets.TWILLIO_ACCOUNT_ID }} \
          QSTASH_TOKEN=${{ secrets.QSTASH_TOKEN }} \
          UNKEY_API_ID=${{ secrets.UNKEY_API_ID }} \
          JITSU_WRITE_KEY=${{ secrets.JITSU_WRITE_KEY }} \
          SCREENSHOT_SERVICE_URL=${{ secrets.SCREENSHOT_SERVICE_URL }} \
          JITSU_HOST=${{ secrets.JITSU_HOST }} \
          CRON_SECRET=${{ secrets.CRON_SECRET }} \
          FLY_REGION=${{ secrets.FLY_REGION }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --config apps/server/fly.toml \
          --dockerfile apps/server/Dockerfile --remote-only --wait-timeout=500
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
